"""Initial migration

Revision ID: 087b644b5943
Revises: 
Create Date: 2025-10-11 14:43:03.411015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087b644b5943'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NHI', sa.String(length=6), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('contact_info', sa.String(length=100), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=15), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('NHI'),
    sa.UniqueConstraint('username')
    )
    op.create_table('surgeon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('surgeon_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('contact_info', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['surgeon_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('surgeon_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('admitted_from', sa.Enum('ER', 'Clinic', 'Referral', name='admitted_from_enum'), nullable=True),
    sa.Column('discharged_to', sa.Enum('Home', 'Rehab', 'Nursing Home', name='discharged_to_enum'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['surgeon_id'], ['surgeon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('surgeon_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['surgeon_id'], ['surgeon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('surgeon_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_date', sa.DateTime(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['surgeon_id'], ['surgeon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surgery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('surgeon_id', sa.Integer(), nullable=False),
    sa.Column('surgery_date', sa.DateTime(), nullable=False),
    sa.Column('surgery_type', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['surgeon_id'], ['surgeon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surgery_id', sa.Integer(), nullable=False),
    sa.Column('complication_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['surgery_id'], ['surgery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complication')
    op.drop_table('surgery')
    op.drop_table('diagnosis')
    op.drop_table('appointment')
    op.drop_table('admission')
    op.drop_table('surgeon')
    op.drop_table('patient')
    op.drop_table('admin')
    # ### end Alembic commands ###
