"""Add needs_password to user models

Revision ID: d9daea241ee0
Revises: c4e84fe3e8e3
Create Date: 2025-10-27 11:14:47.716549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9daea241ee0'
down_revision = 'c4e84fe3e8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_password', sa.Boolean(), nullable=True))

    with op.batch_alter_table('secretary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_password', sa.Boolean(), nullable=True))

    with op.batch_alter_table('surgeon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surgeon', schema=None) as batch_op:
        batch_op.drop_column('needs_password')

    with op.batch_alter_table('secretary', schema=None) as batch_op:
        batch_op.drop_column('needs_password')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('needs_password')

    # ### end Alembic commands ###
